retrieveUnpackaged/objects/TQB_Ad_Hoc_Entry__c.object
<CustomObject>
    <description>A candidates external (ad hoc) references that may be used for the package review.</description>
    <fields>
        <fullName>TQB_Candidate_Package__c</fullName>
        <label>TQB_Candidate_Package</label>
        <referenceTo>TQB_Candidate_Package__c</referenceTo>
        <relationshipLabel>TQB Ad Hoc Entries</relationshipLabel>
        <relationshipName>TQB_Ad_Hoc_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TQB Ad Hoc Entry</label>
    <nameField>
        <displayFormat>ADHOC-{0000}</displayFormat>
        <label>TQB Ad Hoc User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TQB Ad Hoc Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/TQB_Candidate_Package__c.object
<CustomObject>
    <description>Custom object that stores the Candidate&apos;s promotion package data and related fields.</description>
    <label>TQB Candidate Package</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Candidate Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TQB_Candidate_Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/TQB_Candidate_Questionnaire__c.object
<CustomObject>
    <description>Data object for storing candidate questionnaire data.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <description>A field for the Candidate to answer the question.</description>
        <inlineHelpText>A field for the Candidate to answer the question.</inlineHelpText>
        <label>Answer</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TQB_Candidate_Package__c</fullName>
        <label>TQB_Candidate_Package</label>
        <referenceTo>TQB_Candidate_Package__c</referenceTo>
        <relationshipLabel>TQB Candidate Questionnaires</relationshipLabel>
        <relationshipName>TQB_Candidate_Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TQB Candidate Questionnaire</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>TQB Candidate Questionnaire  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TQB Candidate Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/TQB_Comment__c.object
<CustomObject>
    <description>Stores the comments associated with fields and attachments in the CP.</description>
    <label>TQB Comment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TQB_Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/TQB_Letter_of_Intent__c.object
<CustomObject>
    <description>Letters that candidates fill out and submit to communicate their intent to pursue a promotion.</description>
    <label>TQB Letter of Intent</label>
    <nameField>
        <displayFormat>LOI-{00000000}</displayFormat>
        <label>TQB Letter Of Intent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TQB Letters of Intent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/TQBCPWizardControllerTest.cls
//Developer :Naveen Sadhu
//Test cases for TQBCPWizardController apex server controller

@isTest
public class TQBCPWizardControllerTest {
    
    @isTest static void testGetCandidatePackage() {
        TestDataFactory.createLOIRecords(1);
        Test.startTest();               
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
        Test.stopTest();
        System.assert(cp.Id!=null);
    }        
    
     @isTest static void testSaveCandidatePackage() {
        TestDataFactory.createLOIRecords(1);
        Test.startTest();
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          TQB_Candidate_Package__c cpSaved = TQBCPWizardController.saveCandidatePackage(cp);
        Test.stopTest();
        System.assert(cpSaved.Id!=null);
    }
    
    @isTest static void testCreateCandidatePackage() {
        
        TestDataFactory.createLOIRecords(1);
        Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
        Test.stopTest();
        System.assert(newCP.Id!=null);  
        System.assert(cp.Id!=null);
    }
    
    @isTest static void testvalidateCandidateQuestionnaireTrue() {
        TestDataFactory.createLOIRecords(1);
        Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          TestDataFactoryCPWizard.createCPQuestions(1,cp.Id);
          TQBCPWizardController.validateCandidateQuestionnaire(cp.Id);
        Test.stopTest();        
    }
    /*
    @isTest static void testvalidateCandidateQuestionnaireFalse() {
        String errorMessage;
        try{
             TestDataFactory.createLOIRecords(1);
            Test.startTest();  
              TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
              TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
              TestDataFactoryCPWizard.createCPQuestions(1,cp.Id);
              TQBCPWizardController.validateCandidateQuestionnaire(cp.Id);
              TQBCPWizardController.submitCandidatePackage(cp.Id);
            Test.stopTest();   
        }
        catch(DMLException e) {
            System.debug(e.getDmlMessage(0));
           errorMessage = e.getDmlMessage(0);
        }
        System.assertEquals(errorMessage,'null');
    }*/
    
     @isTest static void testGetCandidateLOI() {
         TestDataFactory.createLOIRecords(1);
        Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          TQB_Letter_of_Intent__c LOI = TQBCPWizardController.getCandidateLOI(cp.Id);
        Test.stopTest();
         System.assert(LOI.Id!=null);      
     }
    
     @isTest static void testGetUserRole() {
         Test.startTest();  
             User loggedInUserRole = TQBCPWizardController.getUserRole();
         Test.stopTest();
         System.assert(loggedInUserRole.UserRole.Name!=null);
     }
    
    @isTest static void testsaveQuest() {
        TestDataFactory.createLOIRecords(1);
        Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          List<TQB_Candidate_Questionnaire__c> questionlist = TestDataFactoryCPWizard.createCPQuestions(1,cp.Id);
          questionlist[0].Answer__c = 'update salesforce';
           TQB_Candidate_Questionnaire__c savedQuestion = TQBCPWizardController.saveQuest(cp.Id, questionlist[0]);
        Test.stopTest();   
         System.assertEquals(savedQuestion.Answer__c,'update salesforce');
    }
    
     @isTest static void testGetCandidateQuestions() {
          TestDataFactory.createLOIRecords(1);
          Integer questionCount = TestDataFactoryCPWizard.getQuestionsByTrack();
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          List<TQB_Candidate_Questionnaire__c> questionlist = TQBCPWizardController.getCandidateQuestions(cp.Id);
         Test.stopTest();   
         System.assertEquals(questionlist.size(),questionCount);
     }
     
    @isTest static void testSaveQuestionCommentServer() {
        TestDataFactory.createLOIRecords(1);
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
           List<TQB_Candidate_Questionnaire__c> questionlist = TestDataFactoryCPWizard.createCPQuestions(1,cp.Id);
           String comment = TQBCPWizardController.saveQuestionCommentServer('hello', 'firstLineSupComment', cp.Id, questionlist[0].Id);
           String updatedComment = TQBCPWizardController.saveQuestionCommentServer('hello Updated', 'firstLineSupComment', cp.Id, questionlist[0].Id);
         Test.stopTest(); 
         System.assertEquals(comment,'hello');
         System.assertEquals(updatedComment,'hello Updated');
    }
    
    
    @isTest static void testPopulateQuestionCommentsServer() {
        TestDataFactory.createLOIRecords(1);
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
           List<TQB_Candidate_Questionnaire__c> questionlist = TestDataFactoryCPWizard.createCPQuestions(1,cp.Id);
           String comment = TQBCPWizardController.saveQuestionCommentServer('hello', 'firstLineSupComment', cp.Id, questionlist[0].Id);
           String populatedComment = TQBCPWizardController.populateQuestionCommentsServer(cp.Id , 'firstLineSupComment', questionlist[0].Id);
         Test.stopTest();
        System.assertEquals(comment, populatedComment);
    }
    
    @isTest static void testSaveAdHocEntry() {
        TestDataFactory.createLOIRecords(1);
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          List<TQB_Ad_Hoc_Entry__c> adhocList = TestDataFactoryCPWizard.createCPAdhocs(1,cp.Id);
          TQB_Ad_Hoc_Entry__c adhocEntry = TQBCPWizardController.saveAdHocEntry(cp.Id, adhocList[0], 'insert');
         Test.stopTest();
         System.assert(adhocEntry.Id!=null);
    }
    
    @isTest static void testdeleteAdHoc() { 
        TestDataFactory.createLOIRecords(1);
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          List<TQB_Ad_Hoc_Entry__c> adhocList = TestDataFactoryCPWizard.createCPAdhocs(1,cp.Id);
          TQB_Ad_Hoc_Entry__c adhocEntrySaved = TQBCPWizardController.saveAdHocEntry(cp.Id, adhocList[0], 'insert');
          TQB_Ad_Hoc_Entry__c adhocEntryDeleted = TQBCPWizardController.deleteAdHoc(adhocList[0]);
         Test.stopTest();
         System.debug('saved Entry = ' + adhocEntrySaved.Id);
         System.debug('deleted Entry = ' + adhocEntryDeleted.Id);
         System.assertEquals(adhocEntrySaved.Id, adhocEntryDeleted.Id);
    }
    
    @isTest static void testGetCandidateAdHocEntries() { 
       TestDataFactory.createLOIRecords(1);
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          List<TQB_Ad_Hoc_Entry__c> adhocList = TestDataFactoryCPWizard.createCPAdhocs(1,cp.Id);
          TQB_Ad_Hoc_Entry__c adhocEntrySaved = TQBCPWizardController.saveAdHocEntry(cp.Id, adhocList[0], 'insert');
          List<TQB_Ad_Hoc_Entry__c> getAdhocList = TQBCPWizardController.getCandidateAdHocEntries(cp.Id);
         Test.stopTest();
        System.assertEquals(adhocList.size(), getAdhocList.size());
    }  
    
     @isTest static void testSaveAdHocCommentServer() { 
          TestDataFactory.createLOIRecords(1);
         String testValue = 'hello';
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          TQBCPWizardController.saveAdHocCommentServer(testValue,'firstLineSupComment',cp.Id);
          String commentValue = TQBCPWizardController.populateAdHocCommentsServer(cp.Id,'firstLineSupComment');
         Test.stopTest();
         System.debug('commentvalue = '+ commentValue);
         System.assertEquals(testValue, commentValue);
     }
   
    @isTest static void testSaveReviewCommentAndReturn() { 
        TestDataFactory.createLOIRecords(1);
         String testValue = 'hello';
         Test.startTest();  
          TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
          TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
          List<TQB_Comment__c> commentList = TestDataFactoryCPWizard.createCPComments(1, cp.Id);
          TQBCPWizardController.saveReviewCommentAndReturn(cp.Id, commentList[0]);
          List<TQB_Comment__c> commentListretrieved = TQBCPWizardController.getReviewComments(cp.Id);
         Test.stopTest();
        System.debug('commentList size is ='+commentList);
        System.debug('commentListretrieved size is ='+commentListretrieved.size());
        System.assertEquals(commentList.size(), commentListretrieved.size());
   }
    
    @isTest static void testSaveReviewCommentAndReject() { 
        TestDataFactory.createLOIRecords(1);
         String testValue = 'hello';
         Test.startTest();  
              TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
              TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
              List<TQB_Comment__c> commentList = TestDataFactoryCPWizard.createCPComments(1, cp.Id);
              TQBCPWizardController.saveReviewCommentAndReject(cp.Id, commentList[0],'rejected');
              List<TQB_Comment__c> commentListretrieved = TQBCPWizardController.getReviewComments(cp.Id);
         Test.stopTest();
        System.debug('commentList size is ='+commentList.size());
        System.debug('commentListretrieved size is ='+ commentListretrieved.size());
        System.assertEquals(commentList.size(), commentListretrieved.size());
   }
    
    @isTest static void testGetReviewComments() { 
         TestDataFactory.createLOIRecords(1);
        Test.startTest(); 
           TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
           TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
           List<TQB_Comment__c> commentList = TestDataFactoryCPWizard.createCPReviewComments(1, cp.Id);
            TQBCPWizardController.saveReviewCommentAndReject(cp.Id, commentList[0],'rejected');
           List<TQB_Comment__c> commentListretrieved = TQBCPWizardController.getReviewComments(cp.Id);
        Test.stopTest();
        System.assertEquals(commentList.size(), commentListretrieved.size());
    }
    
    @isTest static void testGetCPStatusPickListValues() { 
         TestDataFactory.createLOIRecords(1);
        Test.startTest(); 
           TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
           TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
           List<String> pickListValueStatuses = TQBCPWizardController.getCPStatusPickListValues();
        Test.stopTest();
        System.assertEquals(pickListValueStatuses.size(),9);
    }
    
    @isTest static void testGetStatePickListValues() { 
         TestDataFactory.createLOIRecords(1);
        Test.startTest(); 
           List<String> pickListValuesState = TQBCPWizardController.getStatePickListValues();
        Test.stopTest();
        System.assertEquals(pickListValuesState.size(),52);
    }
    
    @isTest static void testGet1stLineSupCurrentValue() {
         TestDataFactory.createLOIRecords(1);
        Test.startTest(); 
           TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
           TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
           Id id =  TQBCPWizardController.get1stLineSupCurrentValue(cp.Id);
        Test.stopTest();
         System.assert(id != null);
    }
    
    @isTest static void testGetCPAttachTypePickListValues() {
        TestDataFactory.createLOIRecords(1);
         Test.startTest(); 
            TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
            TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
            List<String> fileTypeCandidate = TQBCPWizardController.getCPAttachTypePickListValues('candidate');
            List<String> fileTypeReviewer = TQBCPWizardController.getCPAttachTypePickListValues('reviewer');
         Test.stopTest();
        System.assertEquals(fileTypeCandidate.size(), 10);
        System.assertEquals(fileTypeReviewer.size(), 2);
    }
    
     @isTest static void testGetRejectReasonValues() {
         TestDataFactory.createLOIRecords(1);
          Test.startTest(); 
            TQB_Candidate_Package__c newCP = TQBCPWizardController.createCandidatePackage();
            TQB_Candidate_Package__c cp = TQBCPWizardController.getOrCreateCandidatePackage(newCP.Id);
            List<String> rejectReasonValues = TQBCPWizardController.getRejectReasonValues();
          Test.stopTest();
         System.assertEquals(rejectReasonValues.size(), 8);
     }
    
    @isTest static void testGetTQBChairPersonList() {
        Test.startTest();
          List<User> tqbChairUsersCreated = TestDataFactory.createTQBChairUser();
          List<User> tqbChairUsers = TQBCPWizardController.getTQBChairPersonList();
        Test.stopTest();
        System.assertEquals(tqbChairUsersCreated.size(), tqbChairUsers.size());
    }
    
    
}